version: '3.8'

services:
  tc31-xar-base1:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /root/ros2_ws
    command: /bin/bash -c "source install/setup.bash && ros2 run py_srvcli client"
    networks:
      - host_network

  talker:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/ros2_ws
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      - PYTHONUNBUFFERED=1
      - ROS_DOMAIN_ID=0
    command: /bin/bash -c "source install/setup.bash && ros2 run cr_robot_ros2 cr_robot_ros2_node"
    networks:
      - host_network

networks:
  host_network:
    external: true
    name: host






